In [1]:
import pandas as pd

In [4]:
'''
   * Open is going to do that, open a file
   * With is going to close the file at the end of the operation. If i dont
   use it then, the file will continue open.
   * is the name i am assigning to the file or the alias where everything
   of the file will be put
   * for i, line in enumerate(f)
   * line is just a variable, like it could be called banana, x etc where
   the content of f is going to be placed. (Typicall loop/for variable)
   * SO in every iteration, there will be put a value into line
   * enumerate will have a control of each line of the file. Is it now
   line 1, line 2, etc...

   python EXAMPLE
for fruit in fruits:              # you get only the item
    print(fruit)

for i, fruit in enumerate(fruits):   # you get the number and the item
    print(i, fruit)

'''

# The following will open the file and will print only the first
# 4 lines of the file
with open('/content/Metadati_PIR.csv', encoding='utf-8-sig') as f:
  for i, line in enumerate(f):
    print(line)
    if i == 4:
      break

VARIABILE_INDICATORE,DEFINIZIONE_INDICATORE,FONTE,ANNO_DI_RIFERIMENTO

cod_rip,Codice Macro-area Geografica,ISTAT,2024

cod_reg,Codice Regione,ISTAT,2024

cod_prov,Codice Provincia,ISTAT,2024

pro_com,Codice ProCom del Comune,ISTAT,2024

In [7]:
# This is the metadata file:

meta = pd.read_csv('/content/Metadati_PIR.csv', encoding='utf-8-sig')
print(meta.shape)
meta.head()

(133, 4)

,VARIABILE_INDICATORE,DEFINIZIONE_INDICATORE,FONTE,ANNO_DI_RIFERIMENTO
0,cod_rip,Codice Macro-area Geografica,ISTAT,2024.0
1,cod_reg,Codice Regione,ISTAT,2024.0
2,cod_prov,Codice Provincia,ISTAT,2024.0
3,pro_com,Codice ProCom del Comune,ISTAT,2024.0
4,macroarea,Nome della Macroarea geografica,NaN,NaN

In [10]:
regioni = pd.read_csv('/content/regioni_pir.csv', encoding='utf-8-sig')
print(regioni.shape)
regioni.head()

(20, 127)

,cod_reg,regione,ar_kmq,ar_id_p3,ar_id_p2,ar_id_p1,aridp3_p,aridp2_p,aridp1_p,pop_res011,...,bbcc_fr_p2,bbcc_fr_p1,bbcc_fr_aa,bbccfrp3p4,bbccfrp4_p,bbccfrp3_p,bbccfrp2_p,bbccfrp1_p,bbccfraa_p,bbccfrp34p
0,1,Piemonte,25386.741,1288.466,2108.220,3294.880,5.075350,8.304414,12.978744,4363916,...,584,0,0,919,2.435093,2.855334,3.361925,0.000000,0.000000,5.290427
1,2,Valle d'Aosta,3260.844,163.880,238.499,300.845,5.025693,7.314027,9.225986,126806,...,143,0,0,119,8.571429,25.428571,40.857143,0.000000,0.000000,34.000000
2,3,Lombardia,23863.092,1877.284,2428.139,4843.379,7.866893,10.175291,20.296527,9704151,...,1508,0,0,408,0.808475,1.087260,7.006784,0.000000,0.000000,1.895735
3,4,Trentino-Alto Adige,13604.701,0.642,351.249,351.282,0.004719,2.581821,2.582063,1029475,...,218,195,0,194,3.141062,7.938321,12.450029,11.136493,0.000000,11.079383
4,5,Veneto,18355.230,1835.938,2435.543,5900.483,10.002261,13.268932,32.146059,4855904,...,96,31,176,111,0.203372,0.207070,0.354977,0.114628,0.650791,0.410442

In [12]:
# I can use the metafile to decode what, for example, ar_km is
meta[meta['VARIABILE_INDICATORE']== 'ar_kmq']

  VARIABILE_INDICATORE DEFINIZIONE_INDICATORE  FONTE  ANNO_DI_RIFERIMENTO
8               ar_kmq       Territorio (kmq)  ISTAT               2024.0

In [13]:
'''
 I use two times meta[meta] because meta['variable' == 'x'] is just the mask.
 by doing meta[meta] is like i am doing meta[mask] otherwise i will get just
 FALSE, TRUE etc.
'''

meta[meta['VARIABILE_INDICATORE'] == 'ar_id_p2']

,VARIABILE_INDICATORE,DEFINIZIONE_INDICATORE,FONTE,ANNO_DI_RIFERIMENTO
10,ar_id_p2,Superficie delle aree a pericolosità idraulica...,ISPRA,2020.0

In [18]:
# Opening the JSON FILE
regions_in_json = pd.read_json('/content/regions.json', encoding='utf-8-sig')
print(regions_in_json.shape)
regions_in_json.head()

(20, 127)

,cod_reg,regione,ar_kmq,ar_id_p3,ar_id_p2,ar_id_p1,aridp3_p,aridp2_p,aridp1_p,pop_res011,...,bbcc_fr_p2,bbcc_fr_p1,bbcc_fr_aa,bbccfrp3p4,bbccfrp4_p,bbccfrp3_p,bbccfrp2_p,bbccfrp1_p,bbccfraa_p,bbccfrp34p
0,1,Piemonte,25386.741,1288.466,2108.220,3294.880,5.075350,8.304414,12.978744,4363916,...,584,0,0,919,2.435093,2.855334,3.361925,0.000000,0.000000,5.290427
1,2,Valle d'Aosta,3260.844,163.880,238.499,300.845,5.025693,7.314027,9.225986,126806,...,143,0,0,119,8.571429,25.428571,40.857143,0.000000,0.000000,34.000000
2,3,Lombardia,23863.092,1877.284,2428.139,4843.379,7.866893,10.175291,20.296527,9704151,...,1508,0,0,408,0.808475,1.087260,7.006784,0.000000,0.000000,1.895735
3,4,Trentino-Alto Adige,13604.701,0.642,351.249,351.282,0.004719,2.581821,2.582063,1029475,...,218,195,0,194,3.141062,7.938321,12.450029,11.136493,0.000000,11.079383
4,5,Veneto,18355.230,1835.938,2435.543,5900.483,10.002261,13.268932,32.146059,4855904,...,96,31,176,111,0.203372,0.207070,0.354977,0.114628,0.650791,0.410442

In [21]:
# OPENING THE EXCEL FILE
regions_in_excell = pd.read_excel('/content/regioni_pir.xlsx.xlsx')
print(regions_in_excell.shape)
regions_in_excell.head()

(20, 127)

,cod_reg,regione,ar_kmq,ar_id_p3,ar_id_p2,ar_id_p1,aridp3_p,aridp2_p,aridp1_p,pop_res011,...,bbcc_fr_p2,bbcc_fr_p1,bbcc_fr_aa,bbccfrp3p4,bbccfrp4_p,bbccfrp3_p,bbccfrp2_p,bbccfrp1_p,bbccfraa_p,bbccfrp34p
0,1,Piemonte,25386.741,1288.466,2108.220,3294.880,5.075350,8.304414,12.978744,4363916,...,584,0,0,919,2.435093,2.855334,3.361925,0.000000,0.000000,5.290427
1,2,Valle d'Aosta,3260.844,163.880,238.499,300.845,5.025693,7.314027,9.225986,126806,...,143,0,0,119,8.571429,25.428571,40.857143,0.000000,0.000000,34.000000
2,3,Lombardia,23863.092,1877.284,2428.139,4843.379,7.866893,10.175291,20.296527,9704151,...,1508,0,0,408,0.808475,1.087260,7.006784,0.000000,0.000000,1.895735
3,4,Trentino-Alto Adige,13604.701,0.642,351.249,351.282,0.004719,2.581821,2.582063,1029475,...,218,195,0,194,3.141062,7.938321,12.450029,11.136493,0.000000,11.079383
4,5,Veneto,18355.230,1835.938,2435.543,5900.483,10.002261,13.268932,32.146059,4855904,...,96,31,176,111,0.203372,0.207070,0.354977,0.114628,0.650791,0.410442

# Opening a file in which there is a problem with the first column

In [1]:
'''
 I can see that the first line is 1,piemonte etc... that is data and
 it cannot be a column so i need to use header.
 SO IF I WANT TO OPEN IT WITH read_csv pandas will take that info as
 columns names
'''

with open('/content/regioni_no_header.csv') as f:
  for i, line in enumerate(f):
    print(line)
    if i == 4:
      break

1,Piemonte,25386.741,4363916,5.08,8.30,

2,Valle d'Aosta,3260.844,126806,5.03,7.31,

3,Lombardia,23863.092,9704151,7.87,10.18,

4,Trentino-Alto Adige,13604.701,1029475,0.00,2.58,"dato provvisorio, da verificare"

5,Veneto,18355.230,4855904,10.00,13.27,

In [4]:
# I can see what happens if i miss the header=NONE
import pandas as pd

regions_no_header = pd.read_csv('/content/regioni_no_header.csv')
regions_no_header.head()

,1,Piemonte,25386.741,4363916,5.08,8.30,Unnamed: 6
0,2,Valle d'Aosta,3260.844,126806,5.03,7.31,NaN
1,3,Lombardia,23863.092,9704151,7.87,10.18,NaN
2,4,Trentino-Alto Adige,13604.701,1029475,0.00,2.58,"dato provvisorio, da verificare"
3,5,Veneto,18355.230,4855904,10.00,13.27,NaN
4,6,Friuli-Venezia Giulia,7924.356,1198753,6.41,9.12,NaN

In [6]:
# I am including header = NONE
regions_no_header = pd.read_csv('/content/regioni_no_header.csv', header=None)
regions_no_header.head()

,0,1,2,3,4,5,6
0,1,Piemonte,25386.741,4363916,5.08,8.30,NaN
1,2,Valle d'Aosta,3260.844,126806,5.03,7.31,NaN
2,3,Lombardia,23863.092,9704151,7.87,10.18,NaN
3,4,Trentino-Alto Adige,13604.701,1029475,0.00,2.58,"dato provvisorio, da verificare"
4,5,Veneto,18355.230,4855904,10.00,13.27,NaN

# PRACTICING SKIPFOOTER

In [8]:
# I am open the the file to see the last lines of if:
with open('/content/regioni_with_footer.csv') as f:
  # I need to read the last lines so I need to use readlines()
  # instead of enumearate()
  lines = f.readlines()

  for line in lines[-6:]:
    print(line)

# I CAN SEE HERE THE THAT LAST 4 LINES IS JUST NOTE OR JUNK:

19,Sicilia,25832.390,4802000,6.28,3.92,-1

20,Sardegna,24100.000,1587413,2.45,4.11,

Totale righe,20

Fonte: dati di esempio per esercizio (non reali)

Generato il 2026-10-21

Nota: -1 = dato non disponibile

In [10]:
# I am going to open it with no skipfooter:
region_with_footer = pd.read_csv('/content/regioni_with_footer.csv')
region_with_footer.tail(5)

# I can see the junk info

,cod_reg,regione,area_kmq,popolazione,frane_pct,alluvioni_pct,note
19,20,Sardegna,24100.0,1587413.0,2.45,4.11,NaN
20,Totale righe,20,NaN,NaN,NaN,NaN,NaN
21,Fonte: dati di esempio per esercizio (non reali),NaN,NaN,NaN,NaN,NaN,NaN
22,Generato il 2026-10-21,NaN,NaN,NaN,NaN,NaN,NaN
23,Nota: -1 = dato non disponibile,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# I am opening it now with skipfooter:
regions_with_no_footer = pd.read_csv('/content/regioni_with_footer.csv', skipfooter=4,engine='python')
regions_with_no_footer.tail()

    cod_reg     regione  area_kmq  popolazione  frane_pct  alluvioni_pct note
15       16      Puglia  19540.90      4008296       3.12           5.47  NaN
16       17  Basilicata  10073.00       562869      16.85           4.90  NaN
17       18    Calabria  15222.10      1844586      11.76           8.30  NaN
18       19     Sicilia  25832.39      4802000       6.28           3.92   -1
19       20    Sardegna  24100.00      1587413       2.45           4.11  NaN